export interface Project {
  id: string; // UUID generated by Supabase
  user_id: string; // Foreign key linking to the user
  project_name: string; // Name of the Supabase project
  supabase_api_key: string; // API key of the project
  created_at: string; // Timestamp of when the project was created
}
